/* Generated by Pyrex 0.9.5.1a on Thu Aug 16 09:33:20 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from bitmatrix */


struct __pyx_obj_9bitmatrix_BitMatrix {
  PyObject_HEAD
  unsigned int (*(*_rows));
  unsigned int _row;
};

static PyTypeObject *__pyx_ptype_9bitmatrix_BitMatrix = 0;
static int __pyx_k1;
static int __pyx_k2;
__PYX_EXTERN_C unsigned int (combinedCardinality(unsigned int (*),unsigned int (*))); /*proto*/
static unsigned int (*(__pyx_f_9bitmatrix_pythonListOfIntsToCIntArray(PyObject *))); /*proto*/


/* Implementation of bitmatrix */

static unsigned int (*__pyx_f_9bitmatrix_pythonListOfIntsToCIntArray(PyObject *__pyx_v_pyList)) {
  unsigned int (*__pyx_v_arrayOfInts);
  int __pyx_v_i;
  PyObject *__pyx_v_number;
  unsigned int (*__pyx_r);
  void (*__pyx_1);
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  unsigned int __pyx_4;
  Py_INCREF(__pyx_v_pyList);
  __pyx_v_number = Py_None; Py_INCREF(Py_None);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":17 */
  __pyx_1 = PyMem_Malloc((100002 * (sizeof(unsigned int )))); if (__pyx_1 == NULL) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  __pyx_v_arrayOfInts = ((unsigned int (*))__pyx_1);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":18 */
  __pyx_v_i = 1;

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":19 */
  __pyx_2 = PyObject_GetIter(__pyx_v_pyList); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
  for (;;) {
    __pyx_3 = PyIter_Next(__pyx_2);
    if (!__pyx_3) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_number);
    __pyx_v_number = __pyx_3;
    __pyx_3 = 0;

    /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":20 */
    __pyx_4 = PyInt_AsUnsignedLongMask(__pyx_v_number); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; goto __pyx_L1;}
    (__pyx_v_arrayOfInts[__pyx_v_i]) = __pyx_4;

    /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":21 */
    __pyx_v_i = (__pyx_v_i + 1);
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":22 */
  (__pyx_v_arrayOfInts[0]) = (__pyx_v_i - 1);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":23 */
  (__pyx_v_arrayOfInts[__pyx_v_i]) = 0xFFFFFFFF;

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":24 */
  __pyx_r = __pyx_v_arrayOfInts;
  goto __pyx_L0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_WriteUnraisable("bitmatrix.pythonListOfIntsToCIntArray");
  __pyx_L0:;
  Py_DECREF(__pyx_v_number);
  Py_DECREF(__pyx_v_pyList);
  return __pyx_r;
}

static int __pyx_f_9bitmatrix_9BitMatrix___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_9bitmatrix_9BitMatrix___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_numberOfDocs;
  int __pyx_r;
  void (*__pyx_1);
  static char *__pyx_argnames[] = {"numberOfDocs",0};
  __pyx_v_numberOfDocs = __pyx_k1;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|i", __pyx_argnames, &__pyx_v_numberOfDocs)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":32 */
  ((struct __pyx_obj_9bitmatrix_BitMatrix *)__pyx_v_self)->_row = 0;

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":33 */
  __pyx_1 = PyMem_Malloc((10000 * (sizeof(unsigned int (*))))); if (__pyx_1 == NULL) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  ((struct __pyx_obj_9bitmatrix_BitMatrix *)__pyx_v_self)->_rows = ((unsigned int (*(*)))__pyx_1);

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("bitmatrix.BitMatrix.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9bitmatrix_9BitMatrix_addRow(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9bitmatrix_9BitMatrix_addRow(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_columnNumbers = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {"columnNumbers",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_columnNumbers)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_columnNumbers);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":36 */
  (((struct __pyx_obj_9bitmatrix_BitMatrix *)__pyx_v_self)->_rows[((struct __pyx_obj_9bitmatrix_BitMatrix *)__pyx_v_self)->_row]) = __pyx_f_9bitmatrix_pythonListOfIntsToCIntArray(__pyx_v_columnNumbers);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":37 */
  ((struct __pyx_obj_9bitmatrix_BitMatrix *)__pyx_v_self)->_row = (((struct __pyx_obj_9bitmatrix_BitMatrix *)__pyx_v_self)->_row + 1);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":38 */
  __pyx_1 = PyLong_FromUnsignedLong((((struct __pyx_obj_9bitmatrix_BitMatrix *)__pyx_v_self)->_row - 1)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("bitmatrix.BitMatrix.addRow");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_columnNumbers);
  return __pyx_r;
}

static PyObject *__pyx_f_9bitmatrix_9BitMatrix_combinedRowCardinalities(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9bitmatrix_9BitMatrix_combinedRowCardinalities(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_columnNumbers = 0;
  int __pyx_v_maxresults;
  unsigned int (*__pyx_v_mask);
  unsigned int __pyx_v_c;
  unsigned int __pyx_v_i;
  PyObject (*__pyx_v_result);
  PyObject *__pyx_r;
  unsigned int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"columnNumbers","maxresults",0};
  __pyx_v_maxresults = __pyx_k2;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|i", __pyx_argnames, &__pyx_v_columnNumbers, &__pyx_v_maxresults)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_columnNumbers);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":46 */
  __pyx_v_mask = __pyx_f_9bitmatrix_pythonListOfIntsToCIntArray(__pyx_v_columnNumbers);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":47 */
  __pyx_v_result = PyList_New(0);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":48 */
  __pyx_1 = ((struct __pyx_obj_9bitmatrix_BitMatrix *)__pyx_v_self)->_row;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":49 */
    __pyx_v_c = combinedCardinality(__pyx_v_mask,(((struct __pyx_obj_9bitmatrix_BitMatrix *)__pyx_v_self)->_rows[__pyx_v_i]));

    /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":50 */
    PyList_Append(__pyx_v_result,PyTuple_Pack(2,PyInt_FromLong(__pyx_v_i),PyInt_FromLong(__pyx_v_c)));
  }

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":52 */
  PyMem_Free(__pyx_v_mask);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":53 */
  __pyx_2 = (PyObject *)__pyx_v_result;
  Py_INCREF(__pyx_2);
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_columnNumbers);
  return __pyx_r;
}

static PyObject *__pyx_n_append;

static PyObject *__pyx_f_9bitmatrix_9BitMatrix_rowCadinalities(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9bitmatrix_9BitMatrix_rowCadinalities(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_result;
  PyObject *__pyx_v_i;
  PyObject *__pyx_v_c;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  long __pyx_2;
  unsigned int __pyx_3;
  int __pyx_4;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_result = Py_None; Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);
  __pyx_v_c = Py_None; Py_INCREF(Py_None);

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":56 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  Py_DECREF(__pyx_v_result);
  __pyx_v_result = __pyx_1;
  __pyx_1 = 0;

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":57 */
  __pyx_3 = ((struct __pyx_obj_9bitmatrix_BitMatrix *)__pyx_v_self)->_row;
  for (__pyx_2 = 0; __pyx_2 < __pyx_3; ++__pyx_2) {
    __pyx_1 = PyInt_FromLong(__pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_1;
    __pyx_1 = 0;

    /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":58 */
    __pyx_4 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_1 = PyLong_FromUnsignedLong(((((struct __pyx_obj_9bitmatrix_BitMatrix *)__pyx_v_self)->_rows[__pyx_4])[0])); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_v_c);
    __pyx_v_c = __pyx_1;
    __pyx_1 = 0;

    /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":59 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_result, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
    Py_INCREF(__pyx_v_i);
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_i);
    Py_INCREF(__pyx_v_c);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_v_c);
    __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
    __pyx_5 = 0;
    __pyx_5 = PyObject_CallObject(__pyx_1, __pyx_6); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
  }

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":60 */
  Py_INCREF(__pyx_v_result);
  __pyx_r = __pyx_v_result;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("bitmatrix.BitMatrix.rowCadinalities");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_result);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_c);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_append, "append"},
  {0, 0}
};

static PyObject *__pyx_tp_new_9bitmatrix_BitMatrix(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  return o;
}

static void __pyx_tp_dealloc_9bitmatrix_BitMatrix(PyObject *o) {
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_9bitmatrix_BitMatrix(PyObject *o, visitproc v, void *a) {
  return 0;
}

static int __pyx_tp_clear_9bitmatrix_BitMatrix(PyObject *o) {
  return 0;
}

static struct PyMethodDef __pyx_methods_9bitmatrix_BitMatrix[] = {
  {"addRow", (PyCFunction)__pyx_f_9bitmatrix_9BitMatrix_addRow, METH_VARARGS|METH_KEYWORDS, 0},
  {"combinedRowCardinalities", (PyCFunction)__pyx_f_9bitmatrix_9BitMatrix_combinedRowCardinalities, METH_VARARGS|METH_KEYWORDS, 0},
  {"rowCadinalities", (PyCFunction)__pyx_f_9bitmatrix_9BitMatrix_rowCadinalities, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_BitMatrix = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_BitMatrix = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_BitMatrix = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_BitMatrix = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9bitmatrix_BitMatrix = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "bitmatrix.BitMatrix", /*tp_name*/
  sizeof(struct __pyx_obj_9bitmatrix_BitMatrix), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9bitmatrix_BitMatrix, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_BitMatrix, /*tp_as_number*/
  &__pyx_tp_as_sequence_BitMatrix, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_BitMatrix, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_BitMatrix, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_9bitmatrix_BitMatrix, /*tp_traverse*/
  __pyx_tp_clear_9bitmatrix_BitMatrix, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9bitmatrix_BitMatrix, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_9bitmatrix_9BitMatrix___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9bitmatrix_BitMatrix, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initbitmatrix(void); /*proto*/
PyMODINIT_FUNC initbitmatrix(void) {
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("bitmatrix", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_9bitmatrix_BitMatrix) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "BitMatrix", (PyObject *)&__pyx_type_9bitmatrix_BitMatrix) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  __pyx_ptype_9bitmatrix_BitMatrix = &__pyx_type_9bitmatrix_BitMatrix;

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":31 */
  __pyx_k1 = 0;

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":40 */
  __pyx_k2 = 0;

  /* "/home/erik/uitwisselplatform/meresco/trunk/src/components/drilldown/bitmatrix/bitmatrix.pyx":55 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("bitmatrix");
}

static char *__pyx_filenames[] = {
  "bitmatrix.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
