find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py core.index.xslice components.lucene.xslice
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py core.index.querywrapper components.lucene.querywrapper
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py core.index.hits components.lucene.hits
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py core.drilldown.drilldown components.drilldown
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.oai.data components.http.oai.data
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.oai.oairecordverb components.http.oai.oairecordverb
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.oai.oaivalidator components.http.oai.oaivalidator
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.oai.oaitool components.http.oai.oaitool
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.partscomponent components.partscomponent
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.undertaker components.undertaker
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.oaigetrecord components.http.oai.oaigetrecord
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.oailist components.http.oai.oailist
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.oaisink components.http.oai.oaisink
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.oailistmetadataformats components.http.oai.oailistmetadataformats
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.portal legacy.deathrow.portal
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.stampcomponent components.stampcomponent
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.oaicomponent components.http.oai.oaicomponent
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.setscomponent components.setscomponent
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.oaiidentify components.http.oai.oaiidentify
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.observers.oailistsets components.http.oai.oailistsets
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.server legacy.deathrow.server
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.pluginregistry legacy.pluginregistry
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py queryserver.plugins legacy.plugins
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.xmlpump components.xmlpump
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.fields2xmlcomponent components.fields2xmlcomponent
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.printingserver legacy.deathrow.printingserver
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.indexcomponent components.lucene.indexcomponent
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.xml2document components.xml2document
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.configuration legacy.configuration
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.logcomponent components.logcomponent
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.teddyinterface legacy.teddyinterface
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.teddygrowlserver components.sshobservableserver
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.teddyinterfaceconstructor legacy.teddyinterfaceconstructor
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.lucenetools components.lucene.lucenetools
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.lucene components.lucene.lucene
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.storagecomponent components.storagecomponent
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.pluginadapter legacy.pluginadapter
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.document components.lucene.document
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.venturi components.venturi
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py teddy.srurecordupdateplugin components.http.srurecordupdateplugin
find -name '*.py' | grep -v svn | xargs ~/scripts/replace.py httpserver.sru components.http
